
resolver: lts-8.9

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0

# resolver: nightly-2016-05-21
